[package]
name = "qvis"
version = "0.1.0"
edition = "2024"

[dependencies]
internment = { version = "0.8.6", features = ["arc"] }
itertools = "0.14.0"
puzzle_theory = { git = "https://github.com/qter-project/puzzle-theory" }
