[package]
name = "calibration_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"

[dependencies.opencv]
version = "0.98.1"
default-features = false
features = ["highgui", "imgcodecs", "imgproc"]
